short_open_tag = On
default_charset = "UTF-8"
session.save_path = "/var/lib/php/session"
display_errors = On
log_errors = On
error_reporting = E_ALL
magic_quotes_gpc = Off
magic_quotes_runtime = Off
magic_quotes_sybase = Off
